server:
  address: 0.0.0.0
  port: 8080
  error:
    whitelabel:
      enabled: false

spring:
  main:
    web-application-type: SERVLET
  application:
    name: auth-service

logging:
  level:
    root: DEBUG
    org:
      springframework:
        security: DEBUG
        web: DEBUG
      hibernate:
        SQL: DEBUG